name: Build Redot Project

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour at the start of the hour
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            scons \
            pkg-config \
            libx11-dev \
            libxcursor-dev \
            libxrandr-dev \
            libxi-dev \
            libgl1-mesa-dev \
            libglu1-mesa-dev \
            build-essential \
            gcc \
            g++ \
            python3

      - name: Clone Redot Engine Source Code
        run: |
          git clone --depth 1 https://github.com/Redot-Engine/redot-engine.git
          cd redot-engine
          git checkout master # Ensure you're on the correct branch

      - name: Build Redot Project
        run: |
          cd redot-engine
          # Build the project for Linux and Windows
          scons platform=linux dev_build=yes
          scons platform=windows dev_build=yes

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: redot-release
          path: redot-engine/bin

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download release artifact
        uses: actions/download-artifact@v4
        with:
          name: redot-release
          path: redot-release

      - name: Get the current date
        id: date
        run: echo "CURRENT_DATE=$(date +'%Y%m%d%H')" >> $GITHUB_ENV

      - name: Zip the release artifact
        run: |
          cd redot-release
          zip -r redot-windows.zip bin/YourWindowsExecutable.exe # Adjust with actual executable name
          zip -r redot-linux.zip bin/YourLinuxExecutable # Adjust with actual executable name

      - name: Upload release build artifacts to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.CURRENT_DATE }}
          name: Release ${{ env.CURRENT_DATE }}
          draft: false
          make_latest: true
          files: |
            redot-windows.zip
            redot-linux.zip
